# YOLO Factchecker Configuration

# YOLO settings
yolo:
  model: "models/yolo/yolov8s.pt"  # Using small model as requested
  confidence_threshold: 0.5
  img_size: 640
  sample_rate: 5  # Process every 5th frame

# Speech recognition settings
speech_recognition:
  language: "en-US"    # Language code (e.g., en-US, fr-FR, de-DE)
  sample_rate: 16000   # Audio sample rate in Hz
  # The following parameters are kept for compatibility but not used
  model_size: "small"  
  device: "cpu"        
  beam_size: 5         
  word_timestamps: true

# Ollama settings
ollama:
  base_url: "http://localhost:11434"
  model: "llama3"
  temperature: 0.2
  max_tokens: 1024

# Processing settings
processing:
  max_upload_size: 500  # MB
  extract_metadata: true
  show_confidence: true
  highlight_issues: true

# Web interface settings
web:
  host: "0.0.0.0"
  port: 5000
  debug: true
